package com.ernestkoko.superpro.data

import android.graphics.Bitmap
import androidx.room.ColumnInfo
import androidx.room.Entity
import androidx.room.PrimaryKey
import java.sql.Blob
import java.util.*

@Entity(tableName = "products_table")
data class Product(
    //product id. It is the primary key and it is autoGenerated
    @PrimaryKey(autoGenerate = true)
    val id: Long = 0,

    //product name
    @ColumnInfo(name = "products_name")
    var productName: String,
    //product image
    @ColumnInfo(name = "product_image")
    var productImage: String? = null,

    //product quantity
    @ColumnInfo(name = "product_quantity")
    var productQuantity: Long = 1,

    //product expiry date
    @ColumnInfo(name = "product_Expiry_date")
    var productExpiryDate: Date?,

    //product manufacturer
    @ColumnInfo(name = "manufacturer")
    var prodManufacturer: String? = null,

    // date of inventory
    @ColumnInfo(name = "inventory_date")
    val productInventoryDate: Long = System.currentTimeMillis()

)

