package com.ernestkoko.superpro.data

import android.graphics.Bitmap
import androidx.room.ColumnInfo
import androidx.room.Entity
import androidx.room.PrimaryKey
import java.sql.Blob
import java.util.*

@Entity(tableName = "products_table")
data class Product(
    //product id. It is the primary key and it is autoGenerated
    @PrimaryKey(autoGenerate = true)
    val id: Long = 0,

    //product name
    @ColumnInfo(name = "products_name")
    var productName: String,
    //product image
    @ColumnInfo(name = "product_image", typeAffinity = ColumnInfo.BLOB)
    var productImage: ByteArray? = null,

    //product quantity
    @ColumnInfo(name = "product_quantity")
    var productQuantity: Long = 1,

    //product expiry date
    @ColumnInfo(name = "product_Expiry_date")
    var productExpiryDate: Date?,

    //product manufacturer
    @ColumnInfo(name = "manufacturer")
    var prodManufacturer: String? = null,

    // date of inventory
    @ColumnInfo(name = "inventory_date")
    val productInventoryDate: Long = System.currentTimeMillis()

) {
    override fun equals(other: Any?): Boolean {
        if (this === other) return true
        if (javaClass != other?.javaClass) return false

        other as Product

        if (id != other.id) return false
        if (productName != other.productName) return false
        if (productImage != null) {
            if (other.productImage == null) return false
            if (!productImage!!.contentEquals(other.productImage!!)) return false
        } else if (other.productImage != null) return false
        if (productQuantity != other.productQuantity) return false
        if (productExpiryDate != other.productExpiryDate) return false
        if (prodManufacturer != other.prodManufacturer) return false
        if (productInventoryDate != other.productInventoryDate) return false

        return true
    }

    override fun hashCode(): Int {
        var result = id.hashCode()
        result = 31 * result + productName.hashCode()
        result = 31 * result + (productImage?.contentHashCode() ?: 0)
        result = 31 * result + productQuantity.hashCode()
        result = 31 * result + (productExpiryDate?.hashCode() ?: 0)
        result = 31 * result + (prodManufacturer?.hashCode() ?: 0)
        result = 31 * result + productInventoryDate.hashCode()
        return result
    }
}
